# Generated by Django 5.1.4 on 2025-07-19 10:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsNextUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password_hash', models.TextField()),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('role', models.CharField(choices=[('user', 'User'), ('organizer', 'Organizer')], default='user', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'whats_next_users',
            },
        ),
        migrations.CreateModel(
            name='WhatsNextWorkshopCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'whats_next_workshop_categories',
            },
        ),
        migrations.CreateModel(
            name='WhatsNextOrganizers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=150, null=True)),
                ('website_url', models.URLField(blank=True, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='version1.whatsnextusers')),
            ],
            options={
                'db_table': 'whats_next_organizers',
            },
        ),
        migrations.CreateModel(
            name='WhatsNextWorkshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('capacity', models.PositiveIntegerField(default=50)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='version1.whatsnextworkshopcategories')),
                ('organizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.whatsnextorganizers')),
            ],
            options={
                'db_table': 'whats_next_workshops',
            },
        ),
        migrations.CreateModel(
            name='WhatsNextReviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.whatsnextusers')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.whatsnextworkshops')),
            ],
            options={
                'db_table': 'whats_next_reviews',
            },
        ),
        migrations.CreateModel(
            name='WhatsNextBookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booked_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('booked', 'Booked'), ('cancelled', 'Cancelled')], default='booked', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.whatsnextusers')),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='version1.whatsnextworkshops')),
            ],
            options={
                'db_table': 'whats_next_bookings',
            },
        ),
    ]
