# Generated by Django 5.1.4 on 2025-07-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsnextworkshops',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='workshop_posters/'),
        ),
    ]
