# Generated by Django 5.1.4 on 2025-07-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('version1', '0002_whatsnextworkshops_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsnextworkshops',
            name='instructor_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
